import Head from 'next/head'
import { Inter } from 'next/font/google'
import { Box } from '@mui/material'
import MediaCard from './components/card'
import axios from 'axios'
import SearchComponent from './components/searchbar'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home({blogs}) {
  const [searchTerm, setSearchTerm] = useState('');

  const handleSearch = (event) => {
    setSearchTerm(event.target.value);
  };
  return (
    <>
      <Head>
        <title>Blogger</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box display={"flex"} flexDirection={"column"} gap={4} >

        <Box width={"20%"} margin={"auto"} marginTop={4} >
        <SearchComponent handleSearch={handleSearch} searchTerm={searchTerm} />
        </Box>
        <Box width={"80%"} margin={"auto"} display={"flex"} gap={4} flexWrap={"wrap"} >
          {
            blogs&&blogs?.filter((d)=>{
              const search = searchTerm.toLowerCase();
                  const title = d.title.toLowerCase();
                  if (searchTerm === "") {
                    return d;
                  }
                  return search && title.includes(search);
            }).map((data)=><MediaCard key={data._id} title={data.title} content={data.content} authorId={data.authorId} id ={data._id} />)
            
          }
        </Box>

          </Box>
      </main>
      
    </>
  )
}


export async function getServerSideProps() {
    const res = await axios.get('http://localhost:3000/api/blogs');
    const data = res.data;
    
    return {
      props: {
        blogs: data,
        suppressHydrationWarning: true,
      }
    }
  }
    
 


